name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >> ~/.ssh/config <<END
          Host playground-umc-8th
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            ServerAliveInterval 60
            ServerAliveCountMax 5
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Prepare remote app directory
        run: |
          ssh playground-umc-8th 'sudo mkdir -p /opt/app'
          ssh playground-umc-8th 'sudo chown ubuntu:ubuntu /opt/app'

      - name: Upload app source to EC2
        run: |
          scp -r . playground-umc-8th:/opt/app

      - name: Upload .env to EC2
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" | ssh playground-umc-8th "cat > /opt/app/.env"

      - name: Install dependencies & generate Prisma client
        run: |
          ssh playground-umc-8th '
            cd /opt/app &&
            npm install --no-audit --no-fund &&
            npx prisma generate
          '

      - name: Register systemd service
        run: |
          ssh playground-umc-8th '
            echo "[Unit]
            Description=UMC 8th Project
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/opt/app
            EnvironmentFile=/opt/app/.env
            ExecStart=/usr/bin/npm run start --prefix /opt/app
            Restart=always
            StandardOutput=journal
            StandardError=journal

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service > /dev/null
          '

      - name: Enable and restart systemd service
        run: |
          ssh playground-umc-8th '
            sudo systemctl daemon-reload &&
            sudo systemctl enable app &&
            sudo systemctl restart app &&
            sudo systemctl status app --no-pager
          '
